#                                           VIEWS

#   -   View is where we find the User Interface.

#   - You can find the Views folder in your Rails App following this path:  nameofyourproject/app/views

#           - Inside the Views we will make two Folders: Positions, Players

#                   -Inside the Positions Folder, we going to create two files: Index.html.erb and show.html.erb

#                           -Index.html.erb     -  is where all the Positions will be posted

#                           -show.html.erb      - is where an individual Position is going to be viewed by the user.

#                               - ' erb ' stands for Embedded Ruby



#   -Here is the database we are going to use

=begin
     ** Our table is called 'players'

                    id                      player               number               <----Columns (Left to right)
             _______________________________________________________________
            I    1            I           C.Ronaldo     I         7         I    <--Look at the ' positons ' table, this player can play multiple positions
            I---------------------------------------------------------------I
            I    2            I           Navas         I         1         I
            I---------------------------------------------------------------I
            I    3            I           Bale          I         5         I
            |---------------------------------------------------------------I
            I    4            I           J. Mata       I        14         I
            I_______________________________________________________________I
=end

=begin
    #Our table is ' position '

     ** Our table is called 'position'

                    id                      position                  player_id              <----Columns (Left to right)
             _______________________________________________________________________
            I    1            I             Left-Wing          I         1          I
            I-----------------------------------------------------------------------I
            I    2            I             Keeper             I         2          I
            I-----------------------------------------------------------------------I
            I    3            I             Right-Wing         I         1          I   <-- Notice that player with id = 1 can play two positions
            |-----------------------------------------------------------------------I
            I    4            I           Mid-fielder          I        4           I
            ------------------------------------------------------------------------I
            I    5            I           Mid-fielder          I        1           I
            I_______________________________________________________________________I
=end

# Let's do something interesting.

#           - Let's say we are working on ' show.html.erb'

#   - All you have to write to SHOW an individual positions is this


                    <!DOCTYPE html >
                    <html>
                        <head><title> Real Madrid </title> </head>
                        <body>
                            <header>.... </header>

                        #here we are fetching the position and store it in a variable
                            <% position = Position.find(1) %>

                        #here we are calling the variable(position) and passing the attribute(position) we want to print. (columns line-41)
                        # the " = " sign means that want to print the position to be view in the browser

                            <h2><%= position.position%></h2>

                            #here we want to also show the player, who plays the position

                            <p> Position of: <%=  position.player%> </p>

                        </body>
                    </html>


# All the HTML above is a lot to write. In Rails you can avoid repetion.

#   - Rails have a folder in the views here is the path to find it:  app/views/layouts/application.html.erb
#       - application.html.erb cointains this code and is generated by default, when we create a new Rails app

                    <!DOCTYPE html >
                    <html>
                        <head><title> Real Madrid </title> </head>
                        <body>
                            <header>.... </header>

                            <%= yield %>  # this mean that whatever we wirte in show.html.erb, can use this layout.

                       </body>

                    </html>

#So delete this code from your show.html.erb. You don't need it

                    <!DOCTYPE html >
                    <html>
                        <head><title> Real Madrid </title> </head>
                        <body>
                            <header>.... </header>

                       </body>

                    </html>

# All you need to have in show.html.erb is this....

                    <% position = Position.find(1) %>                       #<-- Since, we haven't talk about Controllers, I wrote this code here throughout this file. However, this line of code shouldn't be here. Look at the basics_controllers.rb for the explanations. More importantly, learn the concept of Views so you can understand Controllers. You will see how the Views code in this file changes when we do controllers. 
                    <h2><%= position.position%></h2>
                    <p> Position of: <%=  position.player%> </p>


# Let make a link. The player should be a link. Let's write this code

        <%= link_to position.player, player_path(position.player) %>


#What is going on in the code above?

#   -link_to  - this helper set's the name of the player as a link
#   -player_path - after the comma, we write the path of that player we want to link to.


# A better way to write the code in line 122

        <%= link_to position.player, position.player %>

#Here is the code to remember

         <% link_to text_to_show, model_instance %>


# When you start your server, the browser should show the player name as a hyperlink.


# If you like to know more about ' link_to ' helper: api.rubyonrails.org.
#    - Then just write " link_to "

# Let's use  this helper "confrim: "

        <% link_to text_to_show, model_instance, confirm: "You sure?" %>

# When you use confirm, you should get a window popping up after clicking the link, with a message "You sure?"

# - Let's List all our Positions.

                <h1> List of Position </h1>
                <table>
                    <tr>
                        <th> Position </th>
                        <th> Player </th>
                    </tr>


#           LIST ALL



#In this loop we are calling the...
#Postion Model,
# ' all ' method will return an ARRAY of all positions,
# 'each ' will go trough each position in our database, and
# '  | positions | ' will act like a varible as a storage
                <% Position.all.each do | positions |%>
                    <tr>
                    #Here we are printing each position
                        <td> <%= positions.postion%></td>
                    #here we are printing each players
                        <td><%= positions.player%></td
                    </tr>
                #we have to call ' end ' to end the loop
                <%end %>
                </table>

# - when you run your rails server, you should see in the browser a table with the positions and players that are in the database.(if there are not player in the database, than you will not see anything, until you create a player with a position)

# - Lets make the positions and the players as a link

                <% Position.all.each do | positions |%>
                    <tr>
                    #Here we are printing each position
                        <td> <%= link_to positions.position,  position%></td>
                    #here we are printing each players
                        <td><%= link_to positions.player, positions.player%></td
                    </tr>
                #we have to call ' end ' to end the loop
                <%end %>
                </table>



# To display something, incase we don't have any players and positions to show, we do this.

                <% all_positions = Position.all %>

                <% all_positions.each do | positions |%>
                    <tr>
                    #Here we are printing each position
                        <td> <%= link_to positions.position,  position%></td>
                    #here we are printing each players
                        <td><%= link_to positions.player, positions.player%></td
                    </tr>
                #we have to call ' end ' to end the loop
                <%end %>

                #here we are calling the variable in line 201

                <% if all_positions.size == 0 %>
                    <em> No positions Found </em>

                </table>


# EDIT OR DELETE  LINKS

# - We have to add two more links

                <% all_positions = Position.all %>

                <% all_positions.each do | positions |%>
                    <tr>
                    #Here we are printing each position
                        <td> <%= link_to positions.position,  position%></td>
                    #here we are printing each players
                        <td><%= link_to positions.player, positions.player%></td
                        <td><%= link_to "Edit", edit_position_path%></td
                        <td><%= link_to "Destroy", position, method: :delete %></td

                    </tr>
                #we have to call ' end ' to end the loop
                <%end %>

                #here we are calling the variable in line 225

                <% if all_positions.size == 0 %>
                    <em> No positions Found </em>

                </table>


# URL GENERATOR METHODS

        Action                                      Code                                       URL

List all positions                              positions_path                              /positions
New position form                               new_position_path                           /position/new


#This following paths need a ' position '

position = Position.find(1)

Show a position                                 position                                    /positions/1
Edit a position                                 edit_position_path(position)                /position/1/edit
Delete a position                               position, method: :delete                   /position/1


# here is the way you should write it.


                                    <% link_to text_we_want_to_show, code %>
